name: BootcampDockerCICD

trigger:
- master
- feature/*

resources:
- repo: self

# Continuous Integration Process...
stages:
- stage: Build
  displayName: Install Docker-Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: "CI-agents"
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: 'docker-registry'
        repository: 'WeightTrackerApp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        
    - upload: k8s
      artifact: k8s
    
  
- stage: Deploy
  displayName: Deploy to Staging
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  variables:
    - group: "Staging-variables"
  jobs:
  - deployment: Deploy
    displayName: 'Deploy to AKS'
    pool:
      name: "CI-agents"
    environment: 'staging.default'
    strategy:
      runOnce: 
        deploy:
          steps:
            - template: $(Pipeline.Workspace)/templates/kubernetes-cd-template.yml