name: BootcampDockerCICD

trigger:
- master
- feature/*

resources:
- repo: self

parameters:
- name: k8s_conn # name of the parameter; required
  type: string # data type of the parameter; required
  default: 'staging-WeightTracker-default-1659376582608'

# Continuous Integration Process..
stages:
- stage: Build
  displayName: Install Docker-Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: "CI-agents"
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: 'docker-registry'
        repository: 'WeightTrackerApp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    - upload: k8s
      artifact: k8s
    
  
- stage: DeployToStaging
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  displayName: Deploy staging stage
  jobs:
  - deployment: Deploy
    displayName: Deploy to staging
    pool:
      name: "CI-agents"
    environment: 'staging.default'
    variables:
      - group: "Staging-variables"
    strategy:
      runOnce:
        deploy:
         steps:
         - bash: |
            echo "##vso[task.setvariable variable=k8s_conn;]taging-WeightTracker-default-1659376582608"
         - template: templates/kubernetes-cd-template.yaml
            # parameters:
            #   k8s_conn: taging-WeightTracker-default-1659376582608
              
