name: BootcampDockerCICD

trigger:
- master
- feature/*

resources:
- repo: self

# Continuous Integration Process..
stages:
- stage: Build
  displayName: Install Docker-Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: "CI-agents"
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: 'docker-registry'
        repository: 'WeightTrackerApp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - script: |
        helm chart save $(build.sourcesdirectory)/helm_charts/ containerregistry555.azurecr.io/weighttrackerapp:latest
      displayName: save the chart and set the alias
    - script: |
        helm chart push containerregistry555.azurecr.io/weighttrackerapp:latest
      displayName: push the chart to acr

    - upload: k8s
      artifact: k8s
    
  
- stage: DeployToStaging
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  displayName: Deploy staging stage
  jobs:
  - deployment: Deploy
    displayName: Deploy to staging
    pool:
      name: "CI-agents"
    environment: 'staging.default'
    variables:
      - group: "Staging-variables"
    strategy:
      runOnce:
        deploy:
         steps:
           - template: templates/kubernetes-cd-template.yaml
