name: BootcampDockerCICD

trigger:
- master
- feature/*

resources:
- repo: self

# Continuous Integration Process..
stages:
- stage: Build
  displayName: Install Docker-Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: "CI-agents"
    steps:
    - task: Docker@2
      displayName: Build and push image
      inputs:
        containerRegistry: 'docker-registry'
        repository: 'WeightTrackerApp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: HelmDeploy@0
      inputs:
        azureContainerRegistry: 'docker-registry'      
        azureResourceGroupForACR: 'NodeWeightTracker-AKS'
        command: 'package'
        chartPath: 'charts/app-chart'
        chartVersion: '$(Build.BuildId)'

    - upload: k8s
      artifact: k8s
    
  
- stage: DeployToStaging
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
  displayName: Deploy staging stage
  jobs:
  - deployment: Deploy
    displayName: Deploy to staging
    pool:
      name: "CI-agents"
    environment: 'staging.default'
    variables:
      - group: "Staging-variables"
    strategy:
      runOnce:
        deploy:
         steps:
           - template: templates/kubernetes-cd-template.yaml
           - task: HelmInstaller@0
             inputs:
               helmVersion: '2.14.1'
               installKubectl: true
           - task: HelmDeploy@0
             inputs:
               azureContainerRegistry: 'docker-registry'
               azureResourceGroupForACR: ''
               azureSubscriptionForACR: ''
               connectionType: 'Kubernetes Service Connection'
               kubernetesServiceConnection: 'staging-WeightTracker-default-1659481280965'
               command: 'install'
               chartType: 'Name'
               chartName: 'postgresql'
               chartVersion: '11.6.23'
               releaseName: 'my-release'
               valueFile: 'db-secret.yml'
