apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    db: postgres
    app: weight-tracker-app
spec:
  containers:
  - name: postgres
    image: postgres:12
    ports:
    - containerPort: 5432
    envFrom:
    - secretRef:
       name: db_secret.yml
---

kind: Service
apiVersion: v1
metadata:
  name: postgres-service
  labels:
    app: weight-tracker-app
spec:
  selector:
    db: postgres
  ports:
    - port: 5432
      targetPort: 5432