apiVersion : apps/v1
kind: Deployment
metadata:
  name: weight-tracker-app 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weight-tracker-app
  template:
    metadata:
      labels:
        app: weight-tracker-app 
    spec:
      containers:
        - name: weight-tracker-app 
          image: containerregistry555.azurecr.io/weighttrackerapp
          imagePullPolicy: "Always"
          ports:
          - containerPort: 8080
          envFrom:
          - secretRef:
             name: secret.yml