apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.app.name }}
spec:
    type: ClusterIP
    ports:
     - protocol: TCP 
       port: 80
       targetPort: 8080
    selector:
        app: {{ .Values.app.name }}